NASHVILLE COVID

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
import numpy as np
from credentials import user, password, server


#test

In [2]:
#connString = "postgres+psycopg2://nss_user:nssAWS2020@nyt-covid-1.csdmctdmvs7t.us-east-1.rds.amazonaws.com:5432/covid_data"
#engine = create_engine(connString)

engine = create_engine("postgres+psycopg2://"+user+":"\
                                            +password+"@"\
                                            +server+":5432/covid_data")

colleges_df = pd.read_sql("SELECT * FROM colleges;", con=engine)

counties_df = pd.read_sql("SELECT * FROM counties;", con=engine)
mask_use_df = pd.read_sql("SELECT * FROM mask_use;", con=engine)
states_df = pd.read_sql("SELECT * FROM states;", con=engine)
us_totals_df = pd.read_sql("SELECT * FROM colleges;", con=engine)

colleges_df

,date,state,county,city,ipeds_id,college,cases,notes
0,2020-11-05,Alabama,Madison,Huntsville,100654,Alabama A&M University,41.0,None
1,2020-11-05,Alabama,Montgomery,Montgomery,100724,Alabama State University,NaN,None
2,2020-11-05,Alabama,Limestone,Athens,100812,Athens State University,23.0,None
3,2020-11-05,Alabama,Lee,Auburn,100858,Auburn University,2047.0,None
4,2020-11-05,Alabama,Montgomery,Montgomery,100830,Auburn University at Montgomery,80.0,None
...,...,...,...,...,...,...,...,...
1768,2020-11-05,Wisconsin,Milwaukee,Milwaukee,240338,Wisconsin Lutheran College,34.0,None
1769,2020-11-05,Wyoming,Natrona,Casper,240505,Casper College,185.0,None
1770,2020-11-05,Wyoming,Goshen,Torrington,240596,Eastern Wyoming College,6.0,None
1771,2020-11-05,Wyoming,Albany,Laramie,240727,University of Wyoming,1012.0,None
1772,2020-11-05,Wyoming,Sweetwater,Rock Springs,240693,Western Wyoming Community College,10.0,None

In [4]:
df_bus = pd.read_csv("data/businesses.csv")
df_clusters = pd.read_csv("data/clusters.csv")
df_violations = pd.read_csv("data/hubNashville__311__Service_Requests.csv")
df_violations = df_violations[df_violations['Request Type']=='COVID-19'].reset_index(drop=True)
df_violations = df_violations[df_violations['Subrequest Type']=='COVID-19 Violations'].reset_index(drop=True)
df_violations = df_violations[['Request #','Request Type','Subrequest Type','Date / Time Opened','Address','City','Council District','ZIP','Latitude','Longitude']]
df_violations.columns = ['request_id','request_type','subrequest_type','date_opened','address','city','district','zip','lat','long']

df_violations['date'] = df_violations.date_opened.str.split().str[0]
df_violations['time'] = df_violations.date_opened.str.split().str[1]

FileNotFoundError: [Errno 2] File data/hubNashville__311__Service_Requests.csv does not exist: 'data/hubNashville__311__Service_Requests.csv'

In [ ]:
df_violations['date']= pd.to_datetime(df_violations['date'])

In [ ]:
#df_violations.head(10)



df_violations['date'].groupby(df_violations.date.dt.to_period("M")).agg('count').plot(kind='barh')

months_in_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']